import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  screen: { flex: 1, backgroundColor: '#f8fafc' },
  content: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 28, paddingVertical: 32 },
  container: { width: '100%', maxWidth: 440, alignSelf: 'center', gap: 12 },
  brand: { width: 64, height: 64, borderRadius: 20, backgroundColor: '#2563eb', justifyContent: 'center', alignItems: 'center', alignSelf: 'center', marginBottom: 4 },
  brandText: { color: '#ffffff', fontSize: 25, fontWeight: '800', letterSpacing: -1 },
  brandName: { textAlign: 'center', color: '#2563eb', letterSpacing: 3, fontSize: 12, fontWeight: '700', marginBottom: 16 },
  title: { color: '#0f172a', fontSize: 29, fontWeight: '700', textAlign: 'center', letterSpacing: -0.7 },
  subtitle: { color: '#64748b', fontSize: 16, textAlign: 'center', marginBottom: 16 },
  form: { gap: 12 },
  label: { color: '#334155', fontSize: 14, fontWeight: '600', marginTop: 4 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 56, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 14, backgroundColor: '#ffffff', paddingHorizontal: 16 },
  input: { flex: 1, fontSize: 16, color: '#0f172a', paddingVertical: 16 },
  primary: { marginTop: 8, borderRadius: 14, backgroundColor: '#2563eb', minHeight: 56, padding: 16, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10 },
  primaryText: { fontSize: 16, color: '#ffffff', fontWeight: '700' },
  dimmed: { opacity: 0.5 },
  divider: { flexDirection: 'row', alignItems: 'center', gap: 16, marginVertical: 16 },
  line: { height: 1, flex: 1, backgroundColor: '#e2e8f0' },
  dividerText: { color: '#94a3b8', fontSize: 13 },
  social: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 14, minHeight: 56, backgroundColor: '#ffffff', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 12, padding: 16 },
  socialText: { color: '#334155', fontWeight: '600', fontSize: 16 },
  unavailable: { color: '#64748b', textAlign: 'center', fontSize: 12, marginBottom: 4 },
  errorBox: { backgroundColor: '#fef2f2', borderRadius: 10, padding: 12, flexDirection: 'row', gap: 8, alignItems: 'center' },
  error: { color: '#b91c1c', fontSize: 14, flex: 1, lineHeight: 20 },
  link: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  linkText: { color: '#2563eb', fontWeight: '600', fontSize: 15 },
  footer: { color: '#94a3b8', textAlign: 'center', fontSize: 12, marginTop: 20 },
});
